language: c
 
before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - sudo add-apt-repository -y ppa:directhex/monoxide 
  - sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - mozroots --import --sync
  - wget http://nuget.org/nuget.exe
  - mono --runtime=v4.0 ./nuget.exe restore allure-csharp-commons/AllureCSharpCommons.sln
  - mono --runtime=v4.0 ./nuget.exe restore MSTestAllureAdapter.sln
  - xbuild MSTestAllureAdapter.sln
  - nunit-console ./MSTestAllureAdapter.Tests/bin/Debug/MSTestAllureAdapter.Tests.dll
